BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Ingredients" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Volume"	INTEGER NOT NULL,
	"Price"	REAL NOT NULL,
	PRIMARY KEY("Id")
);
CREATE TABLE IF NOT EXISTS "Drink" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Status"	INTEGER,
	"NumberOfIngredients"	INTEGER,
	"CreatedAt"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "IngredientsInGlassDrink" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"DrinkId"	INTEGER,
	"IngredientId"	INTEGER,
	"CreatedAt"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("DrinkId") REFERENCES "Drink"("Id") ON UPDATE SET NULL ON DELETE SET NULL,
	FOREIGN KEY("IngredientId") REFERENCES "Ingredients"("Id") ON UPDATE SET NULL ON DELETE SET NULL
);
INSERT INTO "Ingredients" VALUES (1,'',0,'');
COMMIT;
